name: Auto Build ETCD RPM

on:
  push:
    branches: [ "main", "release/**" ]
    tags:
      - "**"
    paths-ignore:
      - "docs/**"
  pull_request:
    types: [ labeled, synchronize ]
    branches: [ "release/**", "main", "dev/**" ]
    paths-ignore:
      - "docs/**"

concurrency:
  group: auto-build-etcd-rpm-${{ github.ref }}
  cancel-in-progress: true

jobs:
  auto_build_etcd_rpm:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ci-build') ||
      contains(github.event.pull_request.labels.*.name, 'ci-all') ||
      github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
    name: auto build etcd rpm package
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: setup go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: "1.19"

      - name: install nfpm
        run: |
          go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest

      - name: Extract etcd version
        id: etcd_version
        shell: bash
        run: |
          echo "##[set-output name=version;]$(cat ./Version)"

      - name: download etcd
        run: |
          export VERSION=${{ steps.etcd_version.outputs.version }}
          wget https://github.com/etcd-io/etcd/releases/download/v${VERSION}/etcd-v${VERSION}-linux-amd64.tar.gz
          tar xzvf etcd-v${VERSION}-linux-amd64.tar.gz
          # mv etcd and etcdctl to current folder
          mv etcd-v${VERSION}-linux-amd64/etcd etcd-v${VERSION}-linux-amd64/etcdctl .

      - name: Build rpm package
        run: |
          export VERSION=${{ steps.etcd_version.outputs.version }}
          
          # build etcd rpm package
          version=${VERSION} nfpm pkg -p rpm -f nfpm.yaml -t etcd-${VERSION}.x86_64.rpm

      - name: Run centos7 docker
        run: |
          docker run --privileged=true -itd -v $PWD:/app --name centos7Instance --net="host" docker.io/centos:7 /usr/sbin/init

      - name: Install rpm package in centos7 container
        run: |
          export VERSION=${{ steps.etcd_version.outputs.version }}
          docker exec centos7Instance bash -c "cd app && yum install -y ./etcd-${VERSION}.x86_64.rpm"
          docker logs centos7Instance
          # run etcd
          docker exec centos7Instance bash -c "systemctl enable etcd.service && systemctl start etcd.service"

      - name: run test case
        run: |
          export VERSION=${{ steps.etcd_version.outputs.version }}
          ./scripts/etcd_test.sh ${VERSION}

      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: "etcd-rpm"
          path: "./etcd-${{ steps.etcd_version.outputs.version }}.x86_64.rpm"
          retention-days: 1

      - name: Push to COS
        # Only triggered on new tag
        if: startsWith(github.ref, 'refs/tags/')
        env:
          SECRET_ID: ${{ secrets.QCLOUD_COS_SECRETID }}
          SECRET_KEY: ${{ secrets.QCLOUD_COS_SECRETKEY }}
          BUCKET: api7-enterprise-1301662268
          ENDPOINT: cos.accelerate.myqcloud.com
        run: |
          sudo pip install coscmd
          coscmd config -a ${SECRET_ID} -s ${SECRET_KEY} -b ${BUCKET} -e ${ENDPOINT}
          coscmd upload ./apisix-build-tools/output/api7-dashboard-${{ steps.etcd_version.outputs.version }}-0.el7.x86_64.rpm  /workflows/rpms/